[ids]
*

[main]

# replace menu key with meta
compose = leftmeta

# tap = esc
# hold = activate "capslock" layer
capslock = overload(capslock, esc)

# capslock layer
# maps held caps to one of the below or control
[capslock:C]

h = left
j = down
k = up
l = right

y = home
u = pageup
i = delete
o = end
m = backspace
n = pagedown
semicolon = enter
